//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMailMa.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HelpdeskEntities : DbContext
    {
        public HelpdeskEntities()
            : base("name=HelpdeskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TRANMA_D> TRANMA_D { get; set; }
        public DbSet<VW_GetMA> VW_GetMA { get; set; }
        public DbSet<VW_GetEmployeeReport> VW_GetEmployeeReport { get; set; }
        public DbSet<VW_GetMailCC> VW_GetMailCC { get; set; }
    }
}
