//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMailMa.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class one_employee
    {
        public int emp_id { get; set; }
        public string emp_code { get; set; }
        public System.DateTime emp_datenow { get; set; }
        public int title_id { get; set; }
        public string emp_firstname { get; set; }
        public string emp_lastname { get; set; }
        public string emp_idcard { get; set; }
        public string emp_fulladdress { get; set; }
        public string emp_tel { get; set; }
        public string emp_email { get; set; }
        public Nullable<System.DateTime> emp_birthday { get; set; }
        public int department_id { get; set; }
        public int position_id { get; set; }
        public int emp_type_id { get; set; }
        public int emp_status_id { get; set; }
        public System.DateTime emp_start_working_day { get; set; }
        public Nullable<System.DateTime> emp_end_working_day { get; set; }
        public Nullable<int> emp_sex_id { get; set; }
        public byte[] emp_image { get; set; }
        public string emp_image_path { get; set; }
        public Nullable<int> approve_by { get; set; }
        public Nullable<bool> emp_prorate_vacation_leave { get; set; }
        public Nullable<bool> emp_prorate_business_leave { get; set; }
    }
}
