//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMailMa.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANMA_D
    {
        public int TRD_KEY { get; set; }
        public Nullable<int> TRD_TRH { get; set; }
        public Nullable<System.DateTime> TRD_CREATE_DATE { get; set; }
        public Nullable<int> TRD_CREATE_BY { get; set; }
        public Nullable<System.DateTime> TRD_UPDATE_DATE { get; set; }
        public Nullable<int> TRD_UPDATE_BY { get; set; }
        public Nullable<bool> TRD_IS_DELETE { get; set; }
        public string TRD_CODE { get; set; }
        public string TRD_PRODUCT_ITEM { get; set; }
        public string TRD_WARRANTY { get; set; }
        public Nullable<int> TRD_QTY { get; set; }
        public string TRD_WAR { get; set; }
        public string TRD_BRAND { get; set; }
        public string TRD_STATUS { get; set; }
        public string TRD_STATUS_VALUE { get; set; }
        public Nullable<System.DateTime> TRD_START_DATE { get; set; }
        public Nullable<System.DateTime> TRD_END_DATE { get; set; }
    }
}
