//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMailMa.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GetMA
    {
        public int TRH_KEY { get; set; }
        public Nullable<System.DateTime> TRH_CREATE_DATE { get; set; }
        public Nullable<int> TRH_CREATE_BY { get; set; }
        public Nullable<System.DateTime> TRH_UPDATE_DATE { get; set; }
        public Nullable<int> TRH_UPDATE_BY { get; set; }
        public string TRH_PO_NO { get; set; }
        public string TRH_CUS_NAME { get; set; }
        public string TRH_END_USER { get; set; }
        public string TRH_PROJECT_NAME { get; set; }
        public string TRH_PROJECT_CODE { get; set; }
        public string TRH_AE_NAME { get; set; }
        public string TRH_VEN_NAME { get; set; }
        public string TRD_BRAND { get; set; }
        public string TRD_STATUS { get; set; }
        public string TRD_STATUS_VALUE { get; set; }
        public string TRH_REMARK { get; set; }
        public Nullable<System.DateTime> TRD_START_DATE { get; set; }
        public Nullable<System.DateTime> TRD_END_DATE { get; set; }
        public string TRD_CODE { get; set; }
        public string TRD_PRODUCT_ITEM { get; set; }
        public Nullable<int> TRD_QTY { get; set; }
        public string TRD_WARRANTY { get; set; }
        public string TRD_WAR { get; set; }
        public string TRSN_CODE { get; set; }
        public string TRH_TYPE { get; set; }
    }
}
