//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMailMa.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GetEmployeeReport
    {
        public int emp_id { get; set; }
        public string emp_email { get; set; }
        public System.DateTime emp_datenow { get; set; }
        public int title_id { get; set; }
        public string emp_firstname { get; set; }
        public string emp_lastname { get; set; }
        public string name_eng { get; set; }
    }
}
