//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMailMa.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GetMailCC
    {
        public int MAIL_KEY { get; set; }
        public Nullable<int> HelpEmp { get; set; }
        public string Employee { get; set; }
        public string EmpMail { get; set; }
        public string EmployeeCC { get; set; }
        public string EmpMailCC { get; set; }
    }
}
